package handlers

// Event is the marker interface implemented by every concrete event type.
//
// EventType returns the snake_case GitHub event type string ("issue_comment",
// "pull_request", etc.) and is used by HandlerRegistry to route to the registered handler.
//
// GetDeliveryID returns a UUID used to correlate logs and traces for one event. For
// webhook-origin events it is the X-GitHub-Delivery header from the inbound request. For
// runner-origin events it is a fresh random UUID generated by the runner translator.
type Event interface {
	EventType() string
	GetDeliveryID() string
}

// EventBase carries fields common to every event. Each concrete event embeds EventBase, and
// the GetDeliveryID() method on EventBase satisfies that part of the Event interface for free.
type EventBase struct {
	DeliveryID string
}

// GetDeliveryID returns the delivery identifier for this event.
func (b EventBase) GetDeliveryID() string { return b.DeliveryID }
